'use strict';
// Functional DOM-handler tests. No browser, external app, network, or outbound link is opened.
const assert=require('node:assert/strict');
const fs=require('node:fs');
const path=require('node:path');
const UI=require('../assets/js/crm-demo-ui.js');
const Store=require('../assets/js/crm-demo-store.js');
const Assisted=require('../assets/js/crm-assisted.js');
const root=path.resolve(__dirname,'..');
class Classes {constructor(){this.values=new Set();}add(v){this.values.add(v);}remove(v){this.values.delete(v);}toggle(v,on){if(on)this.add(v);else this.remove(v);}}
class Element {
  constructor(id){this.id=id;this.value='';this.textContent='';this.innerHTML='';this.className='';this.hidden=false;this.disabled=false;this.open=false;this.dataset={};this.listeners={};this.classList=new Classes();this.attributes={};}
  addEventListener(t,f){(this.listeners[t]??=[]).push(f);}
  async dispatch(t,event={}){for(const f of this.listeners[t]||[])await f(Object.assign({target:this,preventDefault(){}},event));}
  setAttribute(k,v){this.attributes[k]=v;if(k==='open')this.open=true;}
  removeAttribute(k){delete this.attributes[k];if(k==='open')this.open=false;}
  showModal(){this.open=true;}
  close(){this.open=false;}
  querySelector(){return null;}
  focus(){} select(){}
}
class MemoryStorage {constructor(){this.map=new Map();}getItem(k){return this.map.has(k)?this.map.get(k):null;}setItem(k,v){this.map.set(k,String(v));}removeItem(k){this.map.delete(k);}}
function setup(options={}){
  const nodes=new Map(),get=id=>{if(!nodes.has(id))nodes.set(id,new Element(id));return nodes.get(id);};
  const html=fs.readFileSync(path.join(root,'crm-demo.html'),'utf8');for(const m of html.matchAll(/\bid="([^"]+)"/g))get(m[1]);
  const contexts=['patient','doctor'].map(v=>{const e=new Element();e.dataset.contextSwitch=v;return e;}),views=['contacts','tasks','dashboard'].map(v=>{const e=new Element();e.dataset.view=v;return e;});
  const document={body:{dataset:{}},listeners:{},getElementById:get,querySelectorAll:q=>q==='[data-context-switch]'?contexts:q==='[data-view]'?views:[],addEventListener(t,f){(this.listeners[t]??=[]).push(f);}};
  const storage=options.storage||new MemoryStorage(),listeners={},urls=[],revoked=[],clipboard=[];
  const window={document,localStorage:storage,indexedDB:{},location:{href:'https://demo.test/crm-demo.html',hash:''},listeners,navigator:{clipboard:{writeText:async t=>clipboard.push(t)}},URL:{createObjectURL:blob=>{const u='blob:fixture-'+(urls.length+1);urls.push({url:u,blob});return u;},revokeObjectURL:u=>revoked.push(u)},history:{pushState(_s,_t,url){window.location.hash=url;},replaceState(_s,_t,url){window.location.hash=url;}},addEventListener(t,f){(listeners[t]??=[]).push(f);}};
  const app=UI.createApp({window,document,storage,storeModule:Store,assistedModule:Assisted,evidenceModule:options.evidenceModule,readReview:options.readReview,readDocumentReview:options.readDocumentReview,now:()=>new Date('2026-10-09T12:00:00.000Z')});
  async function submit(values={},files={}){const error=new Element(),elements={namedItem:name=>files[name]?{value:'',files:files[name]}:{value:values[name]??''}};const form={elements,classList:new Classes(),querySelector:()=>error,checkValidity:()=>true,reportValidity(){}};let prevented=false;await get('dialogContent').dispatch('submit',{target:form,preventDefault(){prevented=true;}});return {error:error.textContent,prevented,form};}
  async function click(action,id,data={}){const target={dataset:{action,id,...data},disabled:false};target.closest=()=>target;for(const fn of document.listeners.click||[])await fn({target});}
  return {app,get,document,window,storage,submit,click,urls,revoked,clipboard};
}
(async()=>{
  assert.deepEqual(UI.normalizePhone('55 1234 5678'),{e164:'+525512345678',digits:'525512345678'});
  assert.deepEqual(UI.normalizePhone('+1 (202) 555-0101'),{e164:'+12025550101',digits:'12025550101'});
  assert.equal(UI.contactLinks('12025550101').tel,'tel:+12025550101','Stored validated canonical digits yield fixed tel prefix');
  for(const invalid of ['javascript:alert(1)','https://evil.test/525512345678','tel:+525512345678','+52 55 1234 5678?text=payload','+1\n2025550101','++525512345678','0012025550101','123','+0525512345678','+5255111122222','+120255501011'])assert.equal(UI.normalizePhone(invalid),null,invalid);
  for(const input of ['javascript:12025550101','https://wa.me.evil.test/12025550101','12025550101@evil.test'])assert.equal(UI.contactLinks(input),null,input);
  assert.equal(UI.escapeHtml('<img src=x onerror="evil()">'),'&lt;img src=x onerror=&quot;evil()&quot;&gt;');
  const h=setup();assert.match(h.get('contactList').innerHTML,/No hay contactos/);assert.equal(h.document.body.dataset.context,'patient');
  h.app.handlers.newContact();let result=await h.submit({name:'Mariana <demo>',email:'mariana@example.test',phone:'+1 (202) 555-0101',type:'patient',originalSource:'manual'});assert.equal(result.error,'');assert.equal(result.prevented,true);let c=h.app.state.store.listContacts()[0];assert.ok(c);assert.equal(c.accountExists,false);assert.equal(c.assignedKam,'kam_ana');assert.equal(h.get('editorDialog').open,false);assert.match(h.get('contactDetail').innerHTML,/Mariana &lt;demo&gt;/);assert.match(h.get('contactDetail').innerHTML,/href="https:\/\/wa.me\/12025550101"/);assert.match(h.get('contactDetail').innerHTML,/href="tel:\+12025550101"/);
  const beforeActivities=h.app.state.store.listActivities().length;await h.click('copy-phone');assert.deepEqual(h.clipboard,['+12025550101']);assert.equal(h.app.state.store.listActivities().length,beforeActivities,'Copying and opening apps do not create a contact event');
  h.app.handlers.newContact();result=await h.submit({name:'Invalid phone',email:'bad@example.test',phone:'javascript:alert(1)',type:'patient',originalSource:'manual'});assert.match(result.error,/número válido/);assert.equal(h.get('editorDialog').open,true);assert.equal(h.app.state.store.listContacts().length,1);h.app.closeDialog();
  h.app.handlers.newContact(c);const staleRevision=h.app.state.store.snapshot().revision;assert.ok(h.app.state.store.createTask({contactId:c.id,title:'Newer write',dueAt:'2026-10-10T12:00:00Z'},staleRevision).ok);result=await h.submit({name:'Stale name',email:c.email,phone:'+12025550101'});assert.match(result.error,/cambi|actualiz/i);assert.equal(h.app.state.store.getContact(c.id).name,'Mariana <demo>');assert.equal(h.get('editorDialog').open,true);h.app.closeDialog();
  h.app.handlers.changeStage();result=await h.submit({stage:'not_interested',reason:''});assert.ok(result.error);assert.equal(h.app.state.store.getContact(c.id).stage,'new');result=await h.submit({stage:'not_interested',reason:'Fictitious reason only'});assert.equal(result.error,'');assert.equal(h.app.state.store.getContact(c.id).stage,'not_interested');assert.equal(h.app.state.store.getContact(c.id).stageReason,'Fictitious reason only');
  h.app.handlers.taskEditor(null,c.id);result=await h.submit({contactId:c.id,title:'Confirmar horario',dueAt:'2026-10-09T15:00'});assert.equal(result.error,'');let t=h.app.state.store.listTasks().find(t=>t.title==='Confirmar horario');assert.ok(t);assert.equal(UI.taskBucket(t,'2026-10-09T12:00Z'),'today');assert.equal(UI.taskBucket({...t,dueAt:'2026-10-08T12:00Z'},'2026-10-09T12:00Z'),'overdue');
  h.app.handlers.closeTask(t.id);result=await h.submit({reason:''});assert.ok(result.error);result=await h.submit({reason:'Seguimiento resuelto en prueba'});assert.equal(result.error,'');assert.equal(h.app.state.store.listTasks().find(x=>x.id===t.id).closeReason,'Seguimiento resuelto en prueba');
  h.app.handlers.activityEditor();result=await h.submit({type:'call',outcome:'follow_up',note:'Conversación ficticia',contactAt:'2026-10-08T10:00',nextAction:'Volver a llamar',nextActionAt:'2026-10-12T11:30'});assert.equal(result.error,'');let activity=h.app.state.store.listActivities().find(x=>x.type==='call');assert.ok(activity);assert.match(activity.summary,/Conversación ficticia/);assert.equal(activity.contactAt,new Date('2026-10-08T10:00').toISOString());assert.equal(activity.createdAt,'2026-10-09T12:00:00.000Z');assert.equal(h.app.state.store.listTasks().filter(t=>t.title==='Volver a llamar').length,1,'Followup task is created exactly once atomically');
  h.app.handlers.activityEditor();result=await h.submit({type:'call',outcome:'reached',note:'Future',contactAt:'2026-10-10T10:00'});assert.match(result.error,/futuro/);h.app.closeDialog();
  h.app.handlers.beginOnboarding();let exp=Object.values(h.app.state.store.snapshot().expedients)[0];assert.ok(exp);assert.equal(h.get('editorDialog').open,true);result=await h.submit({fullName:c.name,email:c.email,phone:'+12025550101',procedure:'Tratamiento ficticio',requestedAmount:'25000',termMonths:'6',monthlyIncome:'15000',address:'Dirección ficticia',identityReference:'ID-DEMO-ONLY',employment:'Ocupación DEMO'});assert.equal(result.error,'');exp=Object.values(h.app.state.store.snapshot().expedients)[0];assert.equal(exp.fields.procedure,'Tratamiento ficticio');assert.equal(Object.keys(exp.holderActions).length,0,'KAM UI cannot perform holder actions');
  h.app.handlers.inviteHolder();result=await h.submit({email:c.email});assert.equal(result.error,'');assert.match(h.app.state.invite.href,/^asistido-demo.html#invite=/);assert.doesNotMatch(h.app.state.invite.href,/@|mariana/);assert.match(h.get('contactDetail').innerHTML,/No enviado/);
  await h.click('referral');assert.match(h.get('dialogContent').innerHTML,/asistido-demo.html\?mode=self&amp;kind=patient&amp;ref=/);h.app.closeDialog();
  h.app.handlers.myPhone();result=await h.submit({platform:'mac_iphone'});assert.equal(result.error,'');assert.equal(JSON.parse(h.storage.getItem('pulzzo.crm.demo.myphone.kam_ana')).platform,'mac_iphone');h.get('actorSelect').value='kam_luis';await h.get('actorSelect').dispatch('change');assert.equal(h.app.state.actor.id,'kam_luis');assert.equal(h.app.state.store.listContacts().length,0);h.app.handlers.myPhone();assert.match(h.get('dialogContent').innerHTML,/value="copy" selected/);h.app.closeDialog();
  h.app.navigate('patient','contacts',c.id);assert.match(h.get('contactDetail').innerHTML,/Selecciona un contacto/,'Forged or previous owner deep link reveals no contact');h.app.navigate('doctor','dashboard');assert.equal(h.document.body.dataset.context,'doctor');assert.equal(h.get('dashboardView').hidden,false);h.get('dashboardKam').value='kam_ana';await h.get('dashboardKam').dispatch('change');assert.match(h.get('dashboardContent').innerHTML,/sólo puede consultar/);
  h.get('actorSelect').value='admin_demo';await h.get('actorSelect').dispatch('change');h.app.navigate('patient','contacts',c.id);assert.match(h.get('contactDetail').innerHTML,/Reasignar responsable/);h.app.handlers.reassign();result=await h.submit({assignedKam:'kam_luis',reason:'Transferencia ficticia'});assert.equal(result.error,'');assert.equal(h.app.state.store.getContact(c.id).assignedKam,'kam_luis');assert.equal(h.app.state.store.getContact(c.id).originalSource,'manual');
  h.get('actorSelect').value='kam_ana';await h.get('actorSelect').dispatch('change');h.app.navigate('patient','contacts',c.id);assert.match(h.get('contactDetail').innerHTML,/Selecciona un contacto/);assert.doesNotMatch(h.get('contactDetail').innerHTML,/Mariana/);
  // Evidence handlers: real domain linking, awaited races, rollback and Blob lifetime.
  let nextEvidence=0,putGate=null,getGate=null;const evidenceFiles=new Map(),removed=[];
  const evidence={async put(file,context){const id='ev_'+(++nextEvidence),meta={id,name:file.name,mimeType:file.type,size:file.size,uploadedAt:'2026-10-09T12:00:00.000Z',actorId:context.actorId,contactId:context.contactId,activityId:null,documentType:context.documentType};evidenceFiles.set(id,{...meta,blob:new Blob([new Uint8Array(file.size)],{type:file.type})});if(putGate)await putGate;return meta;},async get(id){if(getGate)await getGate;return evidenceFiles.get(id)||null;},async remove(id){removed.push(id);return evidenceFiles.delete(id);}};
  const e=setup({evidenceModule:{createEvidenceStore:()=>evidence}});e.app.handlers.newContact();result=await e.submit({name:'Evidence Demo',email:'evidence@example.test',phone:'+12025550109',type:'patient',originalSource:'manual'});assert.equal(result.error,'');const ec=e.app.state.store.listContacts()[0];e.app.handlers.beginOnboarding();e.app.closeDialog();
  e.app.handlers.uploadDocument();result=await e.submit({label:'identity'},{file:[{name:'identity-demo.png',type:'image/png',size:128}]});assert.equal(result.error,'');let ee=Object.values(e.app.state.store.snapshot().expedients)[0];assert.equal(ee.documents[0].evidenceId,'ev_1');assert.match(e.get('contactDetail').innerHTML,/identity-demo.png/);await e.app.handlers.viewEvidence('ev_1');assert.equal(e.urls.length,1);assert.equal(e.get('editorDialog').open,true);e.app.closeDialog();assert.deepEqual(e.revoked,['blob:fixture-1']);
  e.app.handlers.activityEditor();result=await e.submit({type:'whatsapp',outcome:'reached',note:'Evidencia ficticia de mensaje manual',contactAt:'2026-10-08T10:00'},{evidence:[{name:'chat-demo.png',type:'image/png',size:128}]});assert.equal(result.error,'');let ea=e.app.state.store.listActivities().find(a=>a.type==='whatsapp');assert.equal(ea.evidence[0].id,'ev_2');await e.app.handlers.viewEvidence('ev_2');assert.equal(e.urls.length,2);e.app.closeDialog();assert.equal(e.revoked.length,2);
  let resolvePut;putGate=new Promise(r=>resolvePut=r);e.app.handlers.uploadDocument();const pending=e.submit({label:'identity'},{file:[{name:'stale.png',type:'image/png',size:128}]});await Promise.resolve();assert.equal(e.get('actorSelect').disabled,true);const double=await e.submit({label:'identity'},{file:[{name:'double.png',type:'image/png',size:128}]});assert.equal(double.prevented,true,'Repeated form submits must suppress browser-native navigation');assert.equal(nextEvidence,3,'Repeated save does not upload twice');assert.ok(e.app.state.store.createTask({contactId:ec.id,title:'Conflicting later update',dueAt:'2026-10-10T12:00:00Z'},e.app.state.store.snapshot().revision).ok);resolvePut();result=await pending;putGate=null;assert.match(result.error,/cambi|actualiz/i);assert.ok(removed.includes('ev_3'));assert.equal(Object.values(e.app.state.store.snapshot().expedients)[0].documents.length,1);assert.equal(e.get('actorSelect').disabled,false);e.app.closeDialog();
  let resolveGet;getGate=new Promise(r=>resolveGet=r);const preview=e.app.handlers.viewEvidence('ev_1');e.get('actorSelect').value='kam_luis';await e.get('actorSelect').dispatch('change');resolveGet();await preview;getGate=null;assert.equal(e.urls.length,2,'Changing actor during awaited read cannot expose a Blob');assert.equal(e.app.state.actor.id,'kam_luis');
  e.get('actorSelect').value='kam_ana';await e.get('actorSelect').dispatch('change');e.app.navigate('patient','contacts',ec.id);evidenceFiles.get('ev_1').contactId='other_contact';await e.app.handlers.viewEvidence('ev_1');assert.equal(e.urls.length,2,'Evidence metadata must match exact contact');evidenceFiles.get('ev_1').contactId=ec.id;await e.app.handlers.viewEvidence('ev_1');assert.equal(e.urls.length,3);for(const f of e.window.listeners.storage||[])f({key:Store.STORAGE_KEY});assert.equal(e.revoked.length,3,'Cross-tab change closes preview and revokes URL');
  let finishOlder;const olderGate=new Promise(resolve=>finishOlder=resolve);evidence.get=async id=>{if(id==='ev_1')await olderGate;return evidenceFiles.get(id)||null;};const olderPreview=e.app.handlers.viewEvidence('ev_1');await e.app.handlers.viewEvidence('ev_2');assert.match(e.get('dialogContent').innerHTML,/chat-demo.png/);const latestURLCount=e.urls.length;finishOlder();await olderPreview;assert.equal(e.urls.length,latestURLCount,'Late older preview cannot replace newer view');assert.match(e.get('dialogContent').innerHTML,/chat-demo.png/);e.app.closeDialog();
  let finishDismissed;const dismissedGate=new Promise(resolve=>finishDismissed=resolve);evidence.get=async id=>{await dismissedGate;return evidenceFiles.get(id)||null;};const dismissedPreview=e.app.handlers.viewEvidence('ev_1');e.app.closeDialog();finishDismissed();await dismissedPreview;assert.equal(e.urls.length,latestURLCount,'Dismissed pending preview cannot reopen');assert.equal(e.get('editorDialog').open,false);
  // A submitted holder fixture exercises actual KAM correction UI handlers.
  let review=null,documentReview=null;const r=setup({readReview:()=>review,readDocumentReview:()=>documentReview,evidenceModule:{createEvidenceStore:()=>evidence}});const must=result=>{assert.equal(result.ok,true,result.error);return result.value;};r.app.handlers.newContact();await r.submit({name:'Correction Demo',email:'correction@example.test',phone:'5512348899',type:'patient',originalSource:'manual'});const rc=r.app.state.store.listContacts()[0];r.app.handlers.beginOnboarding();r.app.closeDialog();let re=Object.values(r.app.state.store.snapshot().expedients)[0],revision=()=>r.app.state.store.snapshot().revision;
  const invitation=must(r.app.state.assisted.invite(re.id,{email:rc.email,ttlMinutes:60},revision())),holder={id:'holder_correction',role:'holder',email:rc.email},hs=Store.createStore({storage:r.storage,actor:holder,now:()=>new Date('2026-10-09T12:00:00Z')}),ha=Assisted.createAssisted({store:hs,actor:holder,now:()=>new Date('2026-10-09T12:00:00Z')});const challenge=must(ha.requestDemoVerification({token:invitation.token,email:rc.email})),proof=must(ha.verifyDemoCode(challenge.challengeId,challenge.demoCode));must(ha.claim(invitation.token,{email:rc.email,proofToken:proof.proofToken},revision()));must(ha.editDraft(re.id,{fields:{procedure:'Demo',requestedAmount:20000,termMonths:12,monthlyIncome:15000,address:'Original ficticio',identityReference:'ID-DEMO'},documents:[{label:'identity',fileName:'identity-demo.pdf',evidenceId:'ev_correction',mimeType:'application/pdf',size:120,demo:true}]},revision()));for(const action of ['otp','buroConsent','finalConfirmation'])must(ha.holderAction(re.id,action,{confirmed:true,demo:true},revision()));must(ha.submit(re.id,revision()));const originalSubmission=JSON.stringify(r.app.state.store.snapshot().expedients[re.id].submissionSnapshot);
  review={expedientId:re.id,contactId:rc.id,accountId:holder.id,status:'requested',requestId:'correction_request_1',requestVersion:1,fingerprint:'review-1',allowedFields:['address','monthlyIncome'],baseline:{address:'Original ficticio',monthlyIncome:15000},reason:'Aclarar domicilio e ingreso ficticios',financialLocked:false};r.app.render();assert.match(r.get('contactDetail').innerHTML,/Observaciones del backoffice/);r.app.handlers.refreshCorrections();assert.match(r.get('contactDetail').innerHTML,/Preparar corrección/);r.app.handlers.editCorrection();assert.match(r.get('dialogContent').innerHTML,/name="address"/);assert.match(r.get('dialogContent').innerHTML,/name="monthlyIncome"/);assert.doesNotMatch(r.get('dialogContent').innerHTML,/name="requestedAmount"/);result=await r.submit({address:'Corregido ficticio',monthlyIncome:'16000',requestedAmount:'1'});assert.equal(result.error,'');re=r.app.state.store.snapshot().expedients[re.id];assert.equal(re.correctionDraft.fields.address,'Corregido ficticio');assert.equal(re.correctionDraft.fields.requestedAmount,undefined);assert.equal(re.correctionDraft.fieldHistory.address[0].actorId,'kam_ana');assert.equal(JSON.stringify(re.submissionSnapshot),originalSubmission);assert.equal(re.correctionSubmission,undefined,'KAM capture does not submit correction');
  r.app.handlers.editCorrection();review={...review,fingerprint:'review-2',requestVersion:2};result=await r.submit({address:'Stale correction',monthlyIncome:'17000'});assert.match(result.error,/cambi|vigente/i);r.app.closeDialog();r.app.handlers.refreshCorrections();review={...review,financialLocked:true,fingerprint:'review-3'};r.app.handlers.refreshCorrections();assert.doesNotMatch(r.get('contactDetail').innerHTML,/data-action="edit-correction"/);assert.match(r.get('contactDetail').innerHTML,/aceptación financiera bloquea/);
  r.window.PulzzoCRMOffice={validateExternalReference:(_storage,key,id,c)=>key==='creditId'&&id==='APP_EXACT'&&c.id===rc.id,readDatabase:()=>({patients:[{id:'APP_EXACT',crmIntake:{contactId:rc.id}}],providers:[]}),operationalStatus:()=> 'En evaluación'};r.app.handlers.activityEditor();result=await r.submit({type:'note',outcome:'follow_up',note:'Referencia exacta DEMO',contactAt:'2026-10-08T10:00',creditId:'APP_OTHER'});assert.match(result.error,/referencia no está vinculada/i);result=await r.submit({type:'note',outcome:'follow_up',note:'Referencia exacta DEMO',contactAt:'2026-10-08T10:00',creditId:'APP_EXACT'});assert.equal(result.error,'');assert.equal(r.app.state.store.listActivities().find(a=>a.note==='Referencia exacta DEMO').creditId,'APP_EXACT');
  // Document correction UI: exact observed doc, version history, draft-only KAM, local-file checks.
  evidence.get=async id=>evidenceFiles.get(id)||null;
  evidenceFiles.set('ev_correction',{id:'ev_correction',name:'identity-demo.pdf',mimeType:'application/pdf',size:120,uploadedAt:'2026-10-09T12:00:00.000Z',actorId:holder.id,contactId:rc.id,blob:new Blob([new Uint8Array(120)],{type:'application/pdf'})});
  documentReview={schema:'pulzzo.crm.document-correction.review.v1',demo:true,expedientId:re.id,contactId:rc.id,accountId:holder.id,recordId:'APP_EXACT',kind:'patient',submissionId:'submission_'+re.id,submissionFingerprint:'submitted-1',docId:'DOC_EXACT',documentType:'identity',status:'requested',version:1,requestId:'doc_request_1',nonce:'doc_nonce_1',reason:'Imagen ficticia incompleta',baselineFingerprint:'baseline-doc-1',fingerprint:'doc-review-1',financialLocked:false,activeDocument:{id:'DOC_EXACT',type:'identity',fileName:'identity-demo.pdf',mimeType:'application/pdf',size:120,evidenceId:'ev_correction',status:'pending'},candidate:null,history:[],approvedDocuments:[]};
  r.app.handlers.refreshDocumentCorrections();assert.match(r.get('contactDetail').innerHTML,/Documentos observados/);assert.match(r.get('contactDetail').innerHTML,/DOC_EXACT/);assert.match(r.get('contactDetail').innerHTML,/Reemplazo pendiente/);r.app.handlers.uploadDocumentCorrection();assert.doesNotMatch(r.get('dialogContent').innerHTML,/name="docId"/,'The observed doc ID is never editable');const oldDocumentEvidence=JSON.stringify(r.app.state.store.snapshot().expedients[re.id].documents);result=await r.submit({}, {file:[{name:'identity-replacement.png',type:'image/png',size:256}]});assert.equal(result.error,'');let dre=r.app.state.store.snapshot().expedients[re.id];assert.equal(dre.documentCorrectionDraft.docId,'DOC_EXACT');assert.equal(dre.documentCorrectionDraft.versions.length,1);assert.equal(dre.documentCorrectionDraft.descriptor.actorId,'kam_ana');assert.equal(dre.documentCorrectionSubmission,undefined);assert.equal(JSON.stringify(dre.documents),oldDocumentEvidence);assert.equal(JSON.stringify(dre.submissionSnapshot),originalSubmission);const replacementId=dre.documentCorrectionDraft.descriptor.id;
  await r.app.handlers.viewEvidence(replacementId);assert.match(r.get('dialogContent').innerHTML,/identity-replacement.png/);r.app.closeDialog();await r.app.handlers.viewEvidence('ev_correction');assert.match(r.get('dialogContent').innerHTML,/identity-demo.pdf/);r.app.closeDialog();
  const oldVersions=dre.documentCorrectionDraft.versions.length;r.app.handlers.uploadDocumentCorrection();const originalSet=r.storage.setItem.bind(r.storage);r.storage.setItem=()=>{throw Error('QuotaExceededError');};result=await r.submit({}, {file:[{name:'quota-failed.png',type:'image/png',size:256}]});r.storage.setItem=originalSet;assert.match(result.error,/guardar|almacenamiento|espacio/i);assert.equal(r.app.state.store.snapshot().expedients[re.id].documentCorrectionDraft.versions.length,oldVersions);assert.ok(removed.includes('ev_'+nextEvidence),'Failed state persistence removes orphan replacement');r.app.closeDialog();
  r.app.handlers.uploadDocumentCorrection();documentReview={...documentReview,fingerprint:'doc-review-2',reason:'Observación actualizada'};result=await r.submit({}, {file:[{name:'stale-document.png',type:'image/png',size:256}]});assert.match(result.error,/cambió|vigente/);assert.ok(removed.includes('ev_'+nextEvidence));r.app.closeDialog();r.app.handlers.refreshDocumentCorrections();
  r.app.handlers.uploadDocumentCorrection();const realGet=evidence.get;evidence.get=async id=>{const file=evidenceFiles.get(id);return file?{...file,contactId:'foreign_contact'}:null;};result=await r.submit({}, {file:[{name:'mismatch-document.png',type:'image/png',size:256}]});evidence.get=realGet;assert.match(result.error,/verificarse/);assert.ok(removed.includes('ev_'+nextEvidence));r.app.closeDialog();
  let resumeNavigatedUpload;putGate=new Promise(resolve=>resumeNavigatedUpload=resolve);r.app.handlers.uploadDocumentCorrection();const navigatedUpload=r.submit({}, {file:[{name:'cancelled-by-navigation.png',type:'image/png',size:256}]});await Promise.resolve();r.app.navigate('patient','tasks',rc.id);assert.equal(r.get('editorDialog').open,false);resumeNavigatedUpload();result=await navigatedUpload;putGate=null;assert.match(result.error,/vista cambió/);assert.ok(removed.includes('ev_'+nextEvidence));assert.equal(r.app.state.store.snapshot().expedients[re.id].documentCorrectionDraft.versions.length,oldVersions);assert.equal(r.get('editorDialog').open,false);r.app.navigate('patient','contacts',rc.id);
  const candidate={id:'DOC_EXACT',type:'identity',fileName:'identity-replacement.png',mimeType:'image/png',size:256,evidenceId:replacementId,status:'rejected'};documentReview={...documentReview,status:'rejected',fingerprint:'doc-review-rejected',candidate,history:[{requestId:'doc_request_1',docId:'DOC_EXACT',status:'rejected',reason:'Todavía ilegible (demo)',document:candidate}]};r.app.handlers.refreshDocumentCorrections();assert.match(r.get('contactDetail').innerHTML,/Reemplazo rechazado/);assert.doesNotMatch(r.get('contactDetail').innerHTML,/data-action="upload-document-correction"/);assert.match(r.get('contactDetail').innerHTML,/Historial de versiones y revisión/);assert.equal(r.app.state.store.snapshot().expedients[re.id].documentCorrectionReceipts.doc_request_1.status,'rejected');
  documentReview={...documentReview,status:'requested',requestId:'doc_request_2',nonce:'doc_nonce_2',version:2,fingerprint:'doc-review-new',candidate:null,financialLocked:true};r.app.handlers.refreshDocumentCorrections();assert.doesNotMatch(r.get('contactDetail').innerHTML,/data-action="upload-document-correction"/);assert.match(r.get('contactDetail').innerHTML,/aceptación financiera bloquea nuevos reemplazos/);assert.equal(JSON.stringify(r.app.state.store.snapshot().expedients[re.id].documents),oldDocumentEvidence);assert.ok(r.app.state.store.snapshot().expedients[re.id].documentCorrectionDrafts.doc_request_1);assert.match(r.get('contactDetail').innerHTML,/Captura archivada/);
  const approved={...candidate,status:'approved',uploadedBy:'kam_ana',uploadedAt:'2026-10-09T12:00:00.000Z'};documentReview={...documentReview,status:'approved',financialLocked:false,fingerprint:'doc-review-approved',activeDocument:approved,candidate:null,history:[...documentReview.history,{requestId:'doc_request_2',docId:'DOC_EXACT',status:'approved',reason:'Archivo ficticio validado',document:approved}],approvedDocuments:[{...approved,requestId:'doc_request_2',docId:'DOC_EXACT'}]};r.app.handlers.refreshDocumentCorrections();assert.equal(r.app.state.store.snapshot().expedients[re.id].documentCorrectionReview.status,'approved',r.get('notice').textContent);assert.match(r.get('contactDetail').innerHTML,/Documento aprobado/);assert.match(r.get('contactDetail').innerHTML,/Versión aprobada en backoffice/);assert.equal(r.app.state.store.snapshot().expedients[re.id].documentCorrectionReceipts.doc_request_2.status,'approved');await r.app.handlers.viewEvidence(replacementId);assert.match(r.get('dialogContent').innerHTML,/identity-replacement.png/);r.app.closeDialog();await r.app.handlers.viewEvidence('ev_correction');assert.match(r.get('dialogContent').innerHTML,/identity-demo.pdf/);r.app.closeDialog();
  const html=fs.readFileSync(path.join(root,'crm-demo.html'),'utf8'),js=fs.readFileSync(path.join(root,'assets/js/crm-demo-ui.js'),'utf8'),css=fs.readFileSync(path.join(root,'assets/css/crm-demo.css'),'utf8');
  assert.match(html,/Solo datos ficticios/);assert.match(html,/sin seguridad ni autenticación real/);assert.doesNotMatch(html,/crm-mail\.js/);assert.match(html,/crm-demo-evidence\.js/);assert.match(html,/media-src blob:/);assert.match(html,/frame-src blob:/);assert.match(html,/object-src 'none'/);assert.match(js,/<iframe sandbox/);assert.match(css,/body\[data-context="doctor"\].*--accent:#b95c37/);assert.match(css,/@media\(max-width:680px\)/);assert.doesNotMatch(js,/\bfetch\s*\(|XMLHttpRequest|window\.open|navigator\.mediaDevices/);assert.equal((css.match(/{/g)||[]).length,(css.match(/}/g)||[]).length);
  console.log('PASS: actual CRM DOM event handlers with real domain store: contact create/edit, safe fixed-prefix links, XSS escaping, stale saves, stages with reasons, task create/close, manual activity, assisted draft/invite, referral link, role scoping, reassignment, per-KAM MyPhone, dashboard, navigation, async evidence race/rollback, double-submit suppression, Blob revocation and scoped field/document corrections preserving the submitted baseline and original files. No browser/outbound communication executed.');
})().catch(e=>{console.error(e);process.exitCode=1;});
